language: node_js

node_js:
  - 10

branches:
   only:
      - main

script:
  - npm run test:lint
  - npm run test

jobs:
  include:
  - # Build and deploy release on tags
    if: tag IS present
    deploy:
      edge: true
      provider: npm
      skip_cleanup: true
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
